laungage: node_js
node_js:
  - 14.15.5
cache:
directories:
  - node modules
script:
  - npm test

before_deploy:
  - npm build

deploy:
  provider: script
  script: echo "Add deployment command"
  on:
  branch: main
